SAMPLE_URL: str = 'https://www.youtube.com/watch?v=8HZ4DnVfWYQ'
DEFAULT_EXT: str = 'mp4'
MIME: str = f'video/{DEFAULT_EXT}'
DEFAULT_NAME: str = f'video.{DEFAULT_EXT}'
DEFAULT_AUDIO_NAME: str = 'audio.m4a'
SAVE_PATH: str = '.'
RUTUBE_KEY: str = 'rutube.ru'
VK_KEY: str = 'vk.com'
